hyprpicker: Add missing libGL
Cairo no longer propagates libGL.

/build/source/src/debug/../includes.hpp:30:10: fatal error: GLES3/gl32.h: No such file or directory
   30 | #include <GLES3/gl32.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.